### ISSUE TITLE
cannot enable device events as a trigger

### ISSUE THREAD

**Issue by maltavnieks** [ricott/homey-io.particle#1]
Hi,

I'm using couple Argon devices successfully for sending requests to Particle cloud. Now I need to get triggers to Homey but I'm getting an error when trying to enable device events as a trigger.
Error says:
"Cannot read properties of undefined (reading 'indexOf')"
![IMG_6594](https://user-images.githubusercontent.com/7930252/184105062-d65252b0-b3b7-4189-a045-fc5e301a2771.jpg)

**Comment by ricott** [comment]
Hi!
There is a new test version available, [0.9.8](https://homey.app/a/io.particle/test/).
This bug is fixed incl. some changes to the language in condition/actions.

**Comment by ricott** [comment]
Moved the test version to live today.
